export const programs=[
 {id:'gymnastics',name:'Tumbling',tag:'FIRST ROLLS TO ADVANCED SKILLS',image:'tumbling.jpg',copy:'A strong foundation. A little more courage. Classes that meet your athlete at their level.',icon:'person',levels:[['Beginners · 7 & under','45 minutes','Rolls, handstands and cartwheels, with strength, flexibility and coordination built into the fun.','tumble-beginners'],['Beginners · 7 & up','60 minutes','Structured fundamentals with instruction adapted to each athlete’s abilities.','tumble-beginners'],['Intermediate · ages 7–9','60 minutes','Build on the basics with round-offs, back walkovers and more advanced progressions.','tumble-intermediate'],['Mixed level · ages 7+','75 minutes','For athletes with a foundation in rolls, cartwheels and handstands, ready for their next challenge.','tumble-mixed'],['Advanced · ages 7+','75 minutes','Refine technique and power for back handsprings, tucks, aerials and advanced combinations.','tumble-advanced'],['Elite · Shelton only','75 minutes · ages 7+','High-level passes, layouts, twisting and advanced combinations for experienced athletes.','classes']]},
 {id:'ninja',name:'Ninja / H.E.R.O.S.',tag:'FITNESS DISGUISED AS FUN',image:'community.jpeg',copy:'Climb, balance, navigate. Turn all that energy into strength, coordination and confidence.',icon:'lightning',levels:[['Mini Ninjas','45 minutes · ages 3.5–5','Age-appropriate obstacle and sports conditioning through running, climbing and balancing.','ninja-sport-3-5'],['Beginner Ninjas','45 minutes · ages 5–9','Dynamic obstacle courses, agility drills and body control that carry into other sports.','ninja-sport-5-9']]},
 {id:'preschool',name:'Preschool & tots',tag:'SMALL MOVES. BIG DISCOVERIES.',image:'preschool.jpg',copy:'An encouraging first introduction to movement—for little learners and the grown-ups cheering them on.',icon:'sun',levels:[['Tumble Tots Playgroup','45 minutes · ages 0–3','Open gym exploration for little ones, with opportunities for caregivers to connect.','play-group'],['Tumble Tots','45 minutes · ages 2.5–4','Structured classes exploring rolls, jumps and balance, building independence and body awareness.','tumble-tots']]},
 {id:'private-lessons',name:'Private lessons',tag:'A LITTLE EXTRA ATTENTION',image:'private.jpg',copy:'Individual coaching focused on a specific goal, a new skill or preparation for tryouts.',icon:'target',levels:[]},
 {id:'camps',name:'Camps & clinics',tag:'MORE ROOM FOR ADVENTURE',image:'camps.jpg',copy:'School-break energy, summer friendships and focused skill sessions. Find what’s coming next.',icon:'flag',levels:[]},
 {id:'birthday-parties',name:'Parties & events',tag:'BIG DAY. BIG SMILES.',image:'parties.jpg',copy:'More movement, more memories. Bring the celebration—we’ll bring the tumbling fun.',icon:'confetti',levels:[]}
];
export const locations=[{id:'north-haven',name:'North Haven',address:'73 Washington Avenue',city:'North Haven, CT 06473',email:'jtnorthhaven@justtumblect.com',map:'https://maps.app.goo.gl/1A4t1uYD7Ca2kbVw6',portal:'north-haven-portal'},{id:'shelton',name:'Shelton',address:'415 Howe Avenue, Suite 301',city:'Shelton, CT 06484',email:'jtshelton@justtumblect.com',map:'https://maps.app.goo.gl/VaWnJGmqHbfkhzyB8',portal:'portal'}];
export const reviews=[
 ['Mike C.','They make you feel at home.','“really make you feel at home!”','Company-published Google excerpt',''],
 ['Lindsay C.','A welcoming place to learn.','“the staff is knowledgeable and friendly.”','Company-published Google excerpt',''],
 ['Valerie P.','Something to look forward to.','“different activities each week!”','Company-published guest excerpt',''],
 ['John Collin Jr','Energy with a purpose.','“My son does the ninja classes and he loves it.”','Google excerpt via Birdeye','https://reviews.birdeye.com/just-tumble-llc-155749247159525'],
 ['Anna Stern','Ready for the next class.','“My daughter loves Just Tumble.”','Google excerpt via Birdeye','https://reviews.birdeye.com/just-tumble-llc-155749247159525']
];
